import json
import logging
import os

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from langchain_openai import ChatOpenAI
from pydantic import BaseModel

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("hyperion")

API_KEY = os.environ.get("API_KEY", "")
if not API_KEY:
    log.warning("API_KEY is not set - the service starts, but LLM calls will fail")
BASE_URL = "https://legion1.di.uoa.gr/v1"
MODEL = "llama3.1"

llm = ChatOpenAI(
    model=MODEL,
    base_url=BASE_URL,
    api_key=API_KEY or "missing",  # the client refuses to be built with an empty key
    max_completion_tokens=2048,
)

app = FastAPI(title="Hyperion Agent")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    user_id: str  # a UUID automatically generated by the IDE — use it to keep per-user session memory
    text: str  # the text the user typed in the chat


def sse(payload: dict) -> str:
    return f"data: {json.dumps(payload)}\n\n"


async def generate_reply(request: ChatRequest):
    try:
        async for chunk in llm.astream(request.text):
            if chunk.text:
                yield sse({"response": chunk.text})
    except Exception:
        log.exception("LLM call failed for user %s", request.user_id)
        yield sse({"response": "Sorry, I could not reach the language model. Please try again."})
    yield "data: [DONE]\n\n"


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}


@app.post("/chat")
async def chat(request: ChatRequest):
    return StreamingResponse(generate_reply(request), media_type="text/event-stream")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
