import json
import logging
import time
from collections.abc import AsyncIterator

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("hyperion")

from hyperion import guardrails, llm, prompts, router  # noqa: E402
from hyperion.session import Session, get_session  # noqa: E402

app = FastAPI(title="Hyperion Agent")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    user_id: str  # a UUID automatically generated by the IDE — use it to keep per-user session memory
    text: str  # the text the user typed in the chat


def sse(payload: dict) -> str:
    return f"data: {json.dumps(payload)}\n\n"


async def answer_question(text: str, session: Session) -> AsyncIterator[str]:
    """Stream an answer that sees the session history (RAG context is added in M2)."""
    messages = [("system", prompts.ANSWER_SYSTEM), *session.history, ("user", text)]
    async for chunk in llm.chat_llm.astream(messages):
        if chunk.text:
            yield chunk.text


async def run_turn(text: str, session: Session) -> AsyncIterator[str]:
    """Yield the text increments of one reply. Python owns the control flow."""
    route = guardrails.apply(await router.route(text, session), text)
    log.info("intent=%s slots=%s", route.intent, route.model_dump(exclude={"intent"}, exclude_none=True))

    if route.intent == "off_topic":
        yield prompts.REFUSAL
    elif route.intent == "smalltalk":
        yield prompts.SMALLTALK
    elif route.intent == "question":
        async for piece in answer_question(text, session):
            yield piece
    else:
        yield prompts.NOT_IMPLEMENTED.format(intent=route.intent)


async def generate_reply(request: ChatRequest) -> AsyncIterator[str]:
    session = get_session(request.user_id)
    started = time.perf_counter()
    reply: list[str] = []
    try:
        async for piece in run_turn(request.text, session):
            reply.append(piece)
            yield sse({"response": piece})
    except Exception:
        log.exception("turn failed for user %s", request.user_id)
        reply.append(prompts.LLM_ERROR)
        yield sse({"response": prompts.LLM_ERROR})
    else:
        session.add_turn(request.text, "".join(reply))
    log.info("turn done user=%s latency=%.2fs", request.user_id, time.perf_counter() - started)
    yield "data: [DONE]\n\n"


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}


@app.post("/chat")
async def chat(request: ChatRequest):
    return StreamingResponse(generate_reply(request), media_type="text/event-stream")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
